spring.application.name=gacha
spring.datasource.url=jdbc:postgresql://localhost:5432/pax_gacha
spring.datasource.username=postgres
spring.datasource.password=Shanone22$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
